
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyqfuffazhkjsxmlbhlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cWZ1ZmZhemhranN4bWxiaGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjE4NjYsImV4cCI6MjA2MTE5Nzg2Nn0.AuEjOGULWUOW1wbbM5xS4jOi9aAHTsWc6BQ_5EmVJ18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with explicit type casting to work around type issues
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
