// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzclrkrxqwzajiixgjbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y2xya3J4cXd6YWppaXhnamJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjY3NjIsImV4cCI6MjA2MDgwMjc2Mn0.FyX_7nTfQSEgUKV-kR7WW3cnh3R0zjXkancWVZB6m0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);